insert into Base (id, name) values (1, 'Keith')
insert into Base (id, name) values (2, 'Erwin')
insert into Base (id, name) values (3, 'Jeremy')
insert into Base (id, name) values (4, 'Scott')
insert into Base (id, name) values (5, 'NOng')
insert into Base (id, name) values (6, 'pite')
insert into Base (id, name) values (7, 'milk')